### ISSUE TITLE
License

### ISSUE THREAD

**Issue by PredatorCZ** [aboood40091/WiiU-swizzling-code#1]
Can you please add license to this repo?
Thanks.

**Comment by aboood40091** [comment]
The code is pretty old, tbh.
You should use this instead:
https://github.com/aboood40091/GTX-Extractor/tree/master/addrlib

**Comment by PredatorCZ** [comment]
Thanks, but this repo contains C port, I don't use python. I would need to write my own based on this or arrdlib's version, I had tested C code and it works as it should, old or not.

**Comment by aboood40091** [comment]
The code included in this repository does not include surface info calculation, which is essential for calculating pitch, alignment, and other important stuff.

Your best bet would be porting the following to C. It's the swizzling code in C#, also ported by me:
https://github.com/KillzXGaming/Switch-Toolbox/tree/716d1c45207dcb2579a879ed04eeee8d2b8e040f/Switch_FileFormatsMain/FileFormats/Texture/GTX.cs#L517

**Comment by PredatorCZ** [comment]
Well, looks like I must port your python code into C, a little complication but I'll manage, thank you anyway.
